Sinatraでメモアプリを作る（DB不使用）
naomichi-h/memo_sinatra pull request #1
Opened 2021-05-28 09:08 UTC by naomichi-h

Sinatraでメモアプリを作りました。
データはJSONファイルに保存する形式です。

rubocop-fjordのチェックは全てパス済みです。
ご確認よろしくお願い致します。

2021-05-31 06:47 UTC, komagata commented
<img width="202" alt="スクリーンショット 2021-05-31 15 47 06" src="https://user-images.githubusercontent.com/16577/120151666-7eb16480-c227-11eb-800d-60239cf63231.png">

File changedが630もあるのは何かがおかしいかもです〜

2021-05-31 09:25 UTC, naomichi-h commented
指摘を受けて、[初心者がRailsプロジェクトへの初PRする前に見るチェックリスト \- komagataのブログ](https://docs.komagata.org/5676)を確認し、ファイルを見直しました。
大変失礼致しました。

`bundle install`でインストールされていたgemファイルを削除し、file changedを減らしました。


file changedで一つ、どうしても解決出来ないことがあったので、ここで質問させていただきたいです。
「README.md」に関してです。

file changedで、READMEファイルにインデントに関する差分があったため、これを解消しようと、mainブランチのREADMEファイルにもdevelopブランチのREADMEファイルと同様のインデントを追加し、pushを行いました。

それぞれのブランチのREADMEファイルをみてみると、きちんと変更されているようです。
しかし、プルリクエストには変更が反映されておらず、インデントに関する差分がそのまま残ってしまっています。

[GitHubのプルリクエストで差分が更新されない時 \- Qiita](https://qiita.com/Gro/items/aa0f5147d9e912ee6aea)を参考に、ベースブランチを一度変更してみましたが、変更を反映することが出来ませんでした。

ベースブランチへの変更を反映するためには、どうしたら良いでしょうか？

2021-05-31 14:42 UTC, komagata commented
@naomichi-h プルリクエストは二つのブランチの差分だけが表示されます。（差分がなければそもそもPRを送る意味がないので）

ですので、mainとこちらのブランチ両方にコミットしたのであれば差分が無いので何も表示されないはずです。
READMEを変更したいというのが目的であれば既に何もする必要はないと思います。

2021-05-31 14:46 UTC, komagata requested changes

2021-05-31 14:46 UTC, komagata commented on app.rb
> +  def search_hash_with_id(id)
search_hash_with_idだとhashとidを検索するっていう意味になっちゃうかもです。
コメントの通りだとするとsearch_hash_from_idとかsearch_hash_by_idとかになりそうです〜

2021-05-31 14:46 UTC, komagata commented on app.rb
> +  redirect to('memos')
```suggestion
  redirect to('/memos')
```

2021-06-01 02:16 UTC, naomichi-h commented on app.rb
> +  def search_hash_with_id(id)
その通りですね...。
メソッド名をsearch_hash_by_idに変更しました！
よろしくお願いします。

2021-06-01 02:20 UTC, naomichi-h commented on app.rb
> +  redirect to('memos')
リダイレクトのパスを`memos`から、`/memos`へ修正しました。
よろしくお願いします。

2021-06-01 05:46 UTC, komagata commented
<img width="399" alt="スクリーンショット 2021-06-01 14 44 51" src="https://user-images.githubusercontent.com/16577/120272397-01015d80-c2e8-11eb-8bbb-0b9aee401dea.png">

gitのコミットメッセージはgitリポジトリ自体につくものなので、レビューの内容がこれだけだとわからず、後から見る人にとって謎の情報になってしまうかもです。

例えばgitlabというサービスにリポジトリを移行した場合はgithubのコメントは分かりません。

他にも同じコミットメッセージが続いているコミットを一つにまとめるなど、コミットの粒度も考えて整理してみてください〜

2021-06-02 11:16 UTC, naomichi-h commented
[【初心者向け】「コミットの粒度がわからない問題」の模範解答を考えてみた \- Qiita](https://qiita.com/jnchito/items/40e0c7d32fde352607be)
[Gitのコミットメッセージの書き方 \- Qiita](https://qiita.com/itosho/items/9565c6ad2ffc24c09364)
を参考に、`git rebase -i`を用いて、コミットをまとめました。

よろしくお願いいたします😊

2021-06-04 09:01 UTC, komagata commented
> fix：レビューを受けて、いくつかの修正を行いました 

こちら下記の通りですので修正してみてください〜

> gitのコミットメッセージはgitリポジトリ自体につくものなので、レビューの内容がこれだけだとわからず、後から見る人にとって謎の情報になってしまうかもです。
> 
> 例えばgitlabというサービスにリポジトリを移行した場合はgithubのコメントは分かりません。

2021-06-04 09:29 UTC, naomichi-h commented
> fix：レビューを受けて、いくつかの修正を行いました

をタイトルとして、

> 不要なgemファイルを削除しました。
メソッド名をsearch_hash_with_idからsearch_hash_by_idに変更し、メソッドが呼び出されている箇所も変更後のものに揃えました。
リダイレクトのパスをmemosから、/memosへ修正しました。

という具体的なメッセージを入れてあるのですが、これでは不十分なのでしょうか？

2021-06-04 11:38 UTC, komagata commented
@naomichi-h すみません、タイトル以外を僕が見落としていました。こちらで大丈夫です〜

2021-06-05 10:34 UTC, merged